theme: jekyll-theme-minimal
baseurl: /CleanSCAN
show_downloads: true

logo: /app/src/main/ic_launcher-web.png
title: Clean Scan
description: A simple, smart and efficient document scanner for Android
author:
  name: Shouvik Basu
